nzmgfdprs/Attendance_management_system

WebContent/WEB-INF/view/menu.jsp
=> second commit

WebContent/CSS/login.css, WebContent/WEB-INF/view/login.jsp, src/servlet/Login.java
=> 教師のログインページの作成

WebContent/CSS/attendingstatuscheck.css, WebContent/WEB-INF/view/attendingstatuscheck.jsp, WebContent/WEB-INF/view/login.jsp, src/servlet/AttendingStatusCheck.java
=> 出席情報一覧のページの作成をした。

WebContent/WEB-INF/view/menu.jsp
=> test commit

WebContent/CSS/applicationstatuscheck.css, WebContent/WEB-INF/view/applicationstatuscheck.jsp, src/servlet/ApplicationStatusCheck.java
申請状況確認のservlet、jsp、cssを作成しました。
出席情報確認の公欠申請ありなしのボタンを実装していないため、
ApplicationStatusCheckからコンパイルしてください。
以上です。レビューお願いします。
=> 申請状況確認のページの作成

WebContent/CSS/attendingstatuscheck.css, WebContent/CSS/menu.css, WebContent/WEB-INF/view/menu.jsp
Menuページのservlet、jsp、cssを作成しました。
レビューお願いします。
=> メニューページの作成

WebContent/CSS/barcodereading.css, WebContent/WEB-INF/view/barcodereading.jsp, WebContent/WEB-INF/view/menu.jsp, src/servlet/BarcodeReading.java
BarcodeReading.java、barcodereading.jsp、arcodereading.cssを作成しました。
レビューをお願いいたします。
=> バーコード読み取りページの作成

WebContent/WEB-INF/view/adminmenu.jsp, WebContent/WEB-INF/view/attendingstatuscheck.jsp, src/dao/AmsDAO.java, src/dto/Login.java, src/servlet/AdminMenu.java, src/servlet/AttendingStatusCheck.java
=> 管理者画面（メニュー）を追加しました。

WebContent/WEB-INF/view/adminmenu.jsp, src/dao/AmsDAO.java, src/servlet/AdminMenu.java
AdminMenu.java,adminmenu.jspを作成しました。
確認よろしくお願いします。
=> 管理者メニューを作成(レビューお願い)

WebContent/WEB-INF/view/addcoursesandclasses.jsp, WebContent/WEB-INF/view/adminmenu.jsp, src/dao/AmsDAO.java, src/servlet/AddCoursesAndClasses.java, src/servlet/LogOut.java
=> 管理者機能（コース追加）実装（レビューお願い）

src/dao/AmsDAO.java, src/servlet/AddCoursesAndClasses.java
管理者の機能でクラスを追加した際にアラートを表示するようにしました。
=> データベースにユーザ追加及びアラート表示処理

WebContent/CSS/adminmenu.css, WebContent/WEB-INF/view/adminmenu.jsp
=> 管理者のヘッダーを作成しました。

WebContent/WEB-INF/view/addstudentsandaddteachers.jsp, WebContent/WEB-INF/view/adminmenu.jsp, src/dao/AmsDAO.java, src/dto/CourseData.java, src/servlet/AddStudentsAndAddTeachers.java
=> 管理者機能（生徒追加）実装

WebContent/CSS/addcoursesandclasses.css, WebContent/WEB-INF/view/addcoursesandclasses.jsp
タイトルの通りです。
レビューをお願いします。
確定に変えるに忘れていました。
すみません。
=> addcoursesandclassesのcssを追加しました

WebContent/WEB-INF/view/addstudentsandaddteachers.jsp, src/dao/AmsDAO.java, src/servlet/AddCourses.java, src/servlet/AddTeacher.java
=> 機能を追加しました。

WebContent/CSS/addstudentsandaddteachers.css, WebContent/WEB-INF/view/addcoursesandclasses.jsp, WebContent/WEB-INF/view/addstudentsandaddteachers.jsp
=> addstudentsandaddteachers.cssを追加しました。

WebContent/WEB-INF/view/addstudentsandaddteachers.jsp
レビューお願いします。
ラジオボタンのコードとコースの部分のコードの確認をお願いいたします。
=> addcoursesandclasses.jspの中身を加えました

WebContent/WEB-INF/view/addstudentsandaddteachers.jsp
=> addstudentsandaddteachers.jsp

src/dao/AmsDAO.java, src/servlet/AddCourses.java
=> コースのエラーメッセージを表示できるように追加

WebContent/WEB-INF/view/addstudentsandaddteachers.jsp, WebContent/WEB-INF/view/attendingstatuscheck.jsp, src/servlet/AddTeacher.java
消えた教員追加の機能を再度実装しました。
確認お願いします。
=> 教員の追加機能を実装及び修正

src/dao/AmsDAO.java, src/servlet/AddStudentsAndAddTeachers.java
=> 管理者のエラーメッセージを追加しました。

src/dao/AmsDAO.java, src/servlet/AddCourses.java, src/servlet/AddCoursesAndClasses.java, src/servlet/AddTeacher.java
=> 管理者機能のエラー処理追加

WebContent/WEB-INF/view/menu.jsp, src/servlet/AttendingSchool.java
menu.jspにfocusText()関数を追加しました。
=> メニュー画面を表示した後に自動的にフォーカスを立てるscriptを追加

WebContent/CSS/menu.css, WebContent/WEB-INF/view/menu.jsp, src/servlet/Login.java
=> テキストボックスの非表示

WebContent/WEB-INF/view/attendingschool.jsp
attendingschool.jspにtimeOut関数を追加しました。
=> 出席画面で5秒後たったらメニュー画面へ戻るjavascriptの処理を追加

WebContent/CSS/menu.css
=> テキストフィールドの非表示

WebContent/WEB-INF/view/barcodereading.jsp, WebContent/WEB-INF/view/leaveEarly.jsp, src/dao/AmsDAO.java, src/dto/AttendanceStatus.java, src/servlet/AttendingSchool.java, src/servlet/BarcodeReading.java
=> 生徒のバーコード読み取り機能実装

WebContent/CSS/barcodereading.css, WebContent/CSS/leaveEarly.css, WebContent/CSS/menu.css, WebContent/WEB-INF/view/attendingschool.jsp, WebContent/WEB-INF/view/barcodereading.jsp, WebContent/WEB-INF/view/leaveEarly.jsp, src/servlet/Login.java
=> cssの追加とその他もろもろの修正

WebContent/WEB-INF/view/barcodereading2.jsp, WebContent/WEB-INF/view/barcodereading3.jsp
=> barcodereading2.jsp、barcodereading3.jspの追加

src/dao/AmsDAO.java, src/servlet/AttendingSchool.java
AmsDAO.java,AttendingSchool.javaに処理を追加しました。
=> 授業ごとに出席を登録する処理を追加

src/dao/AmsDAO.java, src/servlet/BarcodeReading.java
=> 早退処理の追加(DAO)

src/dao/AmsDAO.java
AmsDAO.javaのコードが間違っていたので修正しました。
=> 早退後の公欠処理修正

WebContent/CSS/publicapplicationstatus.css, WebContent/WEB-INF/view/barcodereading3.jsp, WebContent/WEB-INF/view/publicapplicationstatus.jsp, src/servlet/PublicApplicationStatus.java
=> 公欠申請状況の画面のCSSの作成

src/servlet/AttendingSchool.java
=> 午後から登校した場合の処理修正

src/dao/AmsDAO.java, src/servlet/AttendingSchool.java, src/servlet/BarcodeReading.java
=> バーコード読み取り処理の見直し

WebContent/CSS/publicapplicationstatus.css, WebContent/WEB-INF/view/publicapplicationstatus.jsp
=> PublicApplicationStatus.javaとPublicApplicationStatus.cssの修正

WebContent/WEB-INF/view/attendingstatuscheck.jsp
=> 一日分の一覧表示機能実装

WebContent/CSS/publicapplication.css, WebContent/WEB-INF/view/barcodereading2.jsp, WebContent/WEB-INF/view/publicapplication.jsp, WebContent/WEB-INF/view/publicapplicationconfirmation.jsp, src/servlet/PublicApplication.java, src/servlet/PublicApplicationConfirmation.java
=> PublicApplication.javaの作成

WebContent/CSS/applicationstatuscheck.css, WebContent/CSS/publicapplication.css, WebContent/CSS/publicapplicationstatus.css, WebContent/WEB-INF/view/applicationstatuscheck.jsp, WebContent/WEB-INF/view/publicapplication.jsp, WebContent/WEB-INF/view/publicapplicationstatus.jsp
=> cssとその他もろもろの修正

WebContent/WEB-INF/view/attendingstatuscheck.jsp, src/dao/AmsDAO.java, src/servlet/AttendingStatusCheck.java
=> 1週間ごとに一覧表示画面の日付を更新する処理を追加

WebContent/WEB-INF/view/attendingstatuscheck.jsp
=> 1日分の出席表示修正

WebContent/WEB-INF/view/attendingstatuscheck.jsp, WebContent/WEB-INF/view/attendingstatuscheckFriday.jsp, WebContent/WEB-INF/view/attendingstatuscheckMonday.jsp, WebContent/WEB-INF/view/attendingstatuscheckSturdaySunday.jsp, WebContent/WEB-INF/view/attendingstatuscheckThursday.jsp, WebContent/WEB-INF/view/attendingstatuscheckTuesday.jsp, WebContent/WEB-INF/view/attendingstatuscheckWednesday.jsp, src/servlet/AttendingStatusCheck.java
教員機能（一覧表示）を実装しました。
レビューお願いします。
=> 教員機能（一覧表示）実装

WebContent/WEB-INF/view/attendingstatuscheckFriday.jsp, WebContent/WEB-INF/view/attendingstatuscheckMonday.jsp, WebContent/WEB-INF/view/attendingstatuscheckSturdaySunday.jsp, WebContent/WEB-INF/view/attendingstatuscheckThursday.jsp, WebContent/WEB-INF/view/attendingstatuscheckTuesday.jsp, WebContent/WEB-INF/view/attendingstatuscheckWednesday.jsp, src/servlet/AttendingStatusCheck.java
一覧表示画面に教員のログアウトボタンを作成しました。
レビューお願いします。
=> 教員のログアウト処理実装

WebContent/WEB-INF/view/attendingstatuscheckFriday.jsp, WebContent/WEB-INF/view/attendingstatuscheckMonday.jsp, WebContent/WEB-INF/view/attendingstatuscheckSturdaySunday.jsp, WebContent/WEB-INF/view/attendingstatuscheckThursday.jsp, WebContent/WEB-INF/view/attendingstatuscheckTuesday.jsp, WebContent/WEB-INF/view/attendingstatuscheckWednesday.jsp
=> 絞込検索見てくれ作成

src/dao/AmsDAO.java
=> 生徒の情報をすべて取得するメソッドを作成

WebContent/CSS/attendingstatuscheck.css
=> 一覧表示の見てくれ完成

WebContent/WEB-INF/view/attendingstatuscheckFriday.jsp, WebContent/WEB-INF/view/attendingstatuscheckMonday.jsp, WebContent/WEB-INF/view/attendingstatuscheckSturdaySunday.jsp, WebContent/WEB-INF/view/attendingstatuscheckThursday.jsp, WebContent/WEB-INF/view/attendingstatuscheckTuesday.jsp, WebContent/WEB-INF/view/attendingstatuscheckWednesday.jsp
=> 出席状況一覧表示画面に生徒の遅刻数、欠席日数を追加

WebContent/WEB-INF/view/attendingstatuscheckFriday.jsp, WebContent/WEB-INF/view/attendingstatuscheckMonday.jsp, WebContent/WEB-INF/view/attendingstatuscheckSturdaySunday.jsp, WebContent/WEB-INF/view/attendingstatuscheckThursday.jsp, WebContent/WEB-INF/view/attendingstatuscheckTuesday.jsp, WebContent/WEB-INF/view/attendingstatuscheckWednesday.jsp, src/servlet/RefineSearch.java
一覧表示で絞込検索をした際にどこの絞込をしているか表示できるようにしました。
=> 一覧表示画面で機能を追加

WebContent/CSS/publicapplication.css, WebContent/WEB-INF/view/publicapplication.jsp
i created publicapplication.css created.
why don't you review this css who i created.
=> publicapplication.css created

WebContent/CSS/publicapplication.css, WebContent/CSS/publicapplicationresult.css, WebContent/WEB-INF/view/publicapplication.jsp, WebContent/WEB-INF/view/publicapplicationconfirmation.jsp, WebContent/WEB-INF/view/publicapplicationresult.jsp, src/servlet/PublicApplicationResult.java
=> 公欠申請のcss完成

WebContent/WEB-INF/view/publicapplicationdelete.jsp, src/dao/AmsDAO.java, src/dto/PublicStatus.java, src/servlet/DeletePublic.java, src/servlet/PublicApplicationStatus.java
=> 公欠申請状況の機能を実装しました

src/dao/AmsDAO.java, src/servlet/DeletePublic.java
=> 公欠申請削除処理実装

WebContent/CSS/publicapplicationstatus.css, WebContent/WEB-INF/view/publicapplication.jsp
=> 生徒の公欠申請状況の確認の画面のcss完成

WebContent/WEB-INF/view/publicapplicationdeleteresult.jsp
=> 公欠削除結果及びcssの画面の作成

WebContent/WEB-INF/view/attendingstatuscheckFriday.jsp, WebContent/WEB-INF/view/attendingstatuscheckMonday.jsp, WebContent/WEB-INF/view/attendingstatuscheckSturdaySunday.jsp, WebContent/WEB-INF/view/attendingstatuscheckThursday.jsp, WebContent/WEB-INF/view/attendingstatuscheckTuesday.jsp, WebContent/WEB-INF/view/attendingstatuscheckWednesday.jsp
=> 1週間分のプログラムに変更を適用

WebContent/WEB-INF/view/publicapplicationdelete.jsp, WebContent/WEB-INF/view/publicapplicationdeleteresult.jsp, WebContent/WEB-INF/view/publicapplicationresult.jsp, WebContent/WEB-INF/view/publicapplicationstatus.jsp, src/servlet/AttendingStatusCheck2.java, src/servlet/DeletePublic.java, src/servlet/PublicApplication.java, src/servlet/PublicApplicationResult.java, src/servlet/PublicApplicationStatus.java
=> 生徒の画面遷移の修正

WebContent/WEB-INF/view/addcoursesandclasses.jsp, src/servlet/AddCoursesAndClasses.java
=> クラス・コースの一覧表示機能実装

src/servlet/ApplicationStatusCheck.java
チェックボックスにチェックが入ってない場合にエラーアラートを表示します。
確認お願いします。
=> チェックボックスにチェックが入っていない場合エラーアラート表示

WebContent/WEB-INF/view/applicationstatuscheckresult.jsp, src/servlet/AttendingStatusCheck2.java
=> 教員が公欠を許可した際に再度一覧画面へ戻す

WebContent/WEB-INF/view/applicationstatuscheck.jsp, WebContent/WEB-INF/view/publicapplicationstatus.jsp, src/dao/AmsDAO.java, src/dto/PublicStatus.java
生徒の公欠申請状況確認画面で自身の公欠が許可されているか否かがわかるようになりました。
レビューお願いします。
=> 生徒が自身の公欠の許可を調べる処理を追加

WebContent/WEB-INF/view/attendingstatuscheckFriday.jsp, WebContent/WEB-INF/view/publicapplicationstatus.jsp
公欠許可されたものに関しては、その情報は削除できないようにしました。
=> 公欠申請状況画面機能追加

WebContent/WEB-INF/view/applicationstatuscheck.jsp, WebContent/WEB-INF/view/attendingstatuscheckFriday.jsp, src/dao/AmsDAO.java, src/servlet/ApplicationStatusCheck.java
=> 教員が公欠許可した際の処理をさらに追加しました。

src/dao/AmsDAO.java, src/servlet/AttendingSchool.java, src/util/BarcodeReadingErrorCheck.java
=> ダブりエラーを実装したい

src/servlet/AttendingSchool.java
=> 生徒がバーコードを2回以上読み込んだ際のアラート表示処理実装

WebContent/CSS/extraTimeBarcodeReading.css, WebContent/CSS/noBarcodeExits.css, WebContent/WEB-INF/view/extraTimeBarcodeReading.jsp, WebContent/WEB-INF/view/noBarcodeExits.jsp, WebContent/WEB-INF/view/sameBarcodeReading.jsp, src/servlet/AttendingSchool.java
暇を持て余し、システム改善点の③④を修正致しました。
確認をよろしくお願いします。
デザインは小成さんに任せます♪
=> 出席管理システム改善点の③④の修正

WebContent/WEB-INF/view/publicapplicationdelete.jsp, WebContent/WEB-INF/view/publicapplicationdeleteresult.jsp, src/servlet/DeletePublic.java
=> 生徒の名前を公欠申請削除画面に表示

src/servlet/BarcodeReading.java, src/servlet/PublicApplication.java, src/servlet/PublicApplicationStatus.java
登校の場合と同じくエラーメッセージを画面で表示するように修正いたしました。
=> エラーメッセージをアラートではなく画面に変更

src/servlet/AttendingSchool.java, src/servlet/PublicApplicationConfirmation.java
=> 生徒の公欠申請に未入力項目チェックを追加

WebContent/WEB-INF/view/publicapplicationdelete.jsp, WebContent/WEB-INF/view/publicapplicationdeleteresult.jsp
=> ボタンメッセージの変更
